apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-11-16T14:43:01Z"
  generation: 1
  labels:
    run: test
  name: test1
  namespace: default
  resourceVersion: "277021"
  selfLink: /apis/apps/v1/namespaces/default/deployments/test1
  uid: e6b62ae8-3d56-4c29-a53c-fd7c21cface5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: test
    spec:
      containers:
      - image: litefunc/simple-httpserver:v1
        imagePullPolicy: IfNotPresent
        name: test
        ports:
        - containerPort: 8088
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
