version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./internal/table.sql:/docker-entrypoint-initdb.d/1-table.sql
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: abcd

